<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>hidden</key>
	<true/>
	<key>name</key>
	<string>GitSavvy Diff</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>source.diff</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Add block</string>
			<key>match</key>
			<string>\{\+.+?\+\}</string>
			<key>name</key>
			<string>markup.inserted.git-savvy.add-block</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Delete block</string>
			<key>match</key>
			<string>\[\-.+?\-\]</string>
			<key>name</key>
			<string>markup.deleted.git-savvy.delete-block</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>git-savvy.diff</string>
	<key>uuid</key>
	<string>20f2a569-f518-4903-bcfd-35df5bdb8f26</string>
</dict>
</plist>
