<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>hidden</key>
	<true/>
	<key>name</key>
	<string>GitSavvy Commit</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>commit header</string>
			<key>match</key>
			<string>^commit</string>
			<key>name</key>
			<string>string.other.quoted-or-unquoted.git-savvy.commit-info</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>author and date info</string>
			<key>match</key>
			<string>^((Author:)|(Date:))</string>
			<key>name</key>
			<string>string.other.quoted-or-unquoted.git-savvy.author-and-date</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(?=diff)</string>
			<key>comment</key>
			<string>diff section</string>
			<key>end</key>
			<string>^$</string>
			<key>name</key>
			<string>meta.git-savvy.commit-diff</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.diff</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>git-savvy.commit</string>
	<key>uuid</key>
	<string>0d4c19fb-b197-4d90-806e-7212e542c86b</string>
</dict>
</plist>
