<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>hidden</key>
	<true/>
	<key>name</key>
	<string>GitSavvy Tags</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>^  BRANCH:</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>comment.git-savvy.tags.summary-header</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Tags view</string>
			<key>end</key>
			<string>^$</string>
			<key>name</key>
			<string>meta.git-savvy.tags-summary</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>root summary</string>
					<key>match</key>
					<string>^  ROOT:.+</string>
					<key>name</key>
					<string>comment.git-savvy.tags.root-summary</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>branch names</string>
					<key>match</key>
					<string>`[A-Za-z\-_/]+`</string>
					<key>name</key>
					<string>constant.other.git-savvy.tags.branch-name</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>ahead or behind</string>
					<key>match</key>
					<string>(ahead)|(behind)</string>
					<key>name</key>
					<string>keyword.other.git-savvy.tags.ahead-behind</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.other.git-savvy.tags.sha1</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>head summary</string>
					<key>match</key>
					<string>^  HEAD:    ([0-9a-f]{7}) .+</string>
					<key>name</key>
					<string>comment.git-savvy.tags.head-commit</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^  (LOCAL):$</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.other.git-savvy.section-header</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>local section</string>
			<key>end</key>
			<string>^$</string>
			<key>name</key>
			<string>meta.git-savvy.tags.section</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.other.git-savvy.tags.sha1</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^    ([0-9a-f]{7}) .+\n$</string>
					<key>name</key>
					<string>meta.git-savvy.tags.tag</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^  (REMOTE) \((.+)\):$</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.other.git-savvy.section-header</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.other.git-savvy.tags.remote-name</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>remote section</string>
			<key>end</key>
			<string>^$</string>
			<key>name</key>
			<string>meta.git-savvy.tags.section</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.other.git-savvy.tags.sha1</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^    ([0-9a-f]{7}) .+\n$</string>
					<key>name</key>
					<string>meta.git-savvy.tags.tag</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^  ####</string>
			<key>comment</key>
			<string>Key-bindings menu</string>
			<key>end</key>
			<string>^-$</string>
			<key>name</key>
			<string>comment.git-savvy.tags.key-bindings-menu</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.type.git-savvy.key-bindings-header-text</string>
						</dict>
					</dict>
					<key>match</key>
					<string>  ## ([A-Z ]+) ##</string>
					<key>name</key>
					<string>meta.git-savvy.key-bindings-header</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.character.git-savvy-key-binding-key</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\[([A-Za-z])\]</string>
					<key>name</key>
					<string>meta.git-savvy.key-bindings-key-stroke</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>git-savvy.tags</string>
	<key>uuid</key>
	<string>a37acb1d-c57c-4f0b-945b-c71234aa0352</string>
</dict>
</plist>
